version: '3'

services:
  db:
    image: postgres:17
    container_name: KALEIDO_SEARCH_DB
    environment:
      - POSTGRES_USER=kaleidosearch
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
      - kaleido-search-pg-data:/var/lib/postgresql/data

  chromadb:
    image: chromadb/chroma:0.6.3
    container_name: KALEIDO_SEARCH_CHROMA
    environment:
      - IS_PERSISTENT=TRUE
    ports:
      - "5000:8000"
    volumes:
      - kaleido-search-chroma-data:/chroma/chroma

volumes:
  kaleido-search-pg-data:
  kaleido-search-chroma-data: